import { FolderTypes } from "@/types/folder.types";
import { FlashcardTypes } from "@/types/flashcard.types";

export const mockFolders: FolderTypes[] = [
  { folderId: "1", folderName: "Animals", description: "Animal vocabulary", flashcardCount: 3, slug: "" },
  { folderId: "2", folderName: "Food", description: "Food vocabulary", flashcardCount: 5, slug: "" },
  { folderId: "3", folderName: "Colors", description: "Color vocabulary", flashcardCount: 4, slug: "" },
  { folderId: "4", folderName: "Countries", description: "Country vocabulary", flashcardCount: 6, slug: "" },
  { folderId: "5", folderName: "Sports", description: "Sport vocabulary", flashcardCount: 2, slug: "" },
];

export const mockFlashcards: Record<string, FlashcardTypes[]> = {
  "1": [
    {
      flashcardId: "hljfsg",
      word: "Cat",
      wordType: "noun",
      definition: ["A small domesticated carnivorous mammal with soft fur."],
      example: "The cat sat on the mat.",
      phonetic: "/kæt/",
      audioUrl: "",
      imageUrl: "./src/assets/cat.jpeg",
      word_vi: "Con mèo",
      wordType_vi: "danh từ",
      definition_vi: ["Một loài động vật có vú ăn thịt nhỏ được thuần hóa với bộ lông mềm."],
      example_vi: "Con mèo ngồi trên thảm.",
      slug: "cat",
    },
    {
      flashcardId: "dfsjg",
      word: "Dog",
      wordType: "noun",
      definition: ["A domesticated carnivorous mammal with a barking sound."],
      example: "The dog barked at the stranger.",
      phonetic: "/dɔɡ/",
      audioUrl: "",
      imageUrl: "./src/assets/dog.jpeg",
      word_vi: "Con chó",
      wordType_vi: "danh từ",
      definition_vi: ["Một loài động vật có vú ăn thịt được thuần hóa với tiếng sủa."],
      example_vi: "Con chó sủa vào người lạ.",
      slug: "dog",
    },
    {
      flashcardId: "adljfhl",
      word: "Bird",
      wordType: "noun",
      definition: ["A warm-blooded egg-laying vertebrate with feathers."],
      example: "The bird flew over the trees.",
      phonetic: "/bɜrd/",
      audioUrl: "",
      imageUrl: "./src/assets/bird.jpeg",
      word_vi: "Con chim",
      wordType_vi: "danh từ",
      definition_vi: ["Một loài động vật có máu nóng đẻ trứng với bộ lông."],
      example_vi: "Con chim bay qua những cái cây.",
      slug: "bird",
    },
  ],
  "2": [
    {
      flashcardId: "food1",
      word: "Pizza",
      wordType: "noun",
      definition: ["A dish of Italian origin consisting of a flat, round base of dough baked with a topping of tomato sauce and cheese."],
      example: "I ordered a large pizza for dinner.",
      phonetic: "/ˈpiːtsə/",
      audioUrl: "",
      imageUrl: "./src/assets/pizza.jpeg",
      word_vi: "Bánh pizza",
      wordType_vi: "danh từ",
      definition_vi: ["Một món ăn có nguồn gốc từ Ý, gồm một đế bánh phẳng, tròn được nướng với sốt cà chua và phô mai."],
      example_vi: "Tôi đã đặt một chiếc pizza lớn cho bữa tối.",
      slug: "pizza",
    },
    {
      flashcardId: "food2",
      word: "Sushi",
      wordType: "noun",
      definition: ["A Japanese dish of prepared vinegared rice, usually with some sugar and salt, accompanied by a variety of ingredients."],
      example: "We had sushi for lunch at the Japanese restaurant.",
      phonetic: "/ˈsuːʃi/",
      audioUrl: "",
      imageUrl: "./src/assets/sushi.jpeg",
      word_vi: "Sushi",
      wordType_vi: "danh từ",
      definition_vi: ["Món ăn Nhật Bản gồm cơm trộn giấm, thường có thêm đường và muối, kèm theo nhiều loại nguyên liệu khác nhau."],
      example_vi: "Chúng tôi đã ăn sushi cho bữa trưa tại nhà hàng Nhật.",
      slug: "sushi",
    }
  ],
  "3": [
    {
      flashcardId: "color1",
      word: "Azure",
      wordType: "noun",
      definition: ["A bright blue color, like that of a cloudless sky."],
      example: "The azure sky was perfect for our beach day.",
      phonetic: "/ˈæʒər/",
      audioUrl: "",
      imageUrl: "./src/assets/azure.jpeg",
      word_vi: "Màu xanh da trời",
      wordType_vi: "danh từ",
      definition_vi: ["Màu xanh dương sáng, giống như màu bầu trời không mây."],
      example_vi: "Bầu trời xanh da trời hoàn hảo cho ngày đi biển của chúng tôi.",
      slug: "azure",
    },
    {
      flashcardId: "color2",
      word: "Crimson",
      wordType: "noun",
      definition: ["A rich deep red color inclining to purple."],
      example: "The autumn leaves turned a beautiful crimson.",
      phonetic: "/ˈkrɪmzən/",
      audioUrl: "",
      imageUrl: "./src/assets/crimson.jpeg",
      word_vi: "Màu đỏ thẫm",
      wordType_vi: "danh từ",
      definition_vi: ["Màu đỏ đậm pha tím."],
      example_vi: "Lá mùa thu chuyển sang màu đỏ thẫm đẹp mắt.",
      slug: "crimson",
    }
  ],
  "4": [
    {
      flashcardId: "country1",
      word: "Japan",
      wordType: "noun",
      definition: ["An island country in East Asia, known for its unique culture and technological advancement."],
      example: "Japan is famous for its cherry blossoms in spring.",
      phonetic: "/dʒəˈpæn/",
      audioUrl: "",
      imageUrl: "./src/assets/japan.jpeg",
      word_vi: "Nhật Bản",
      wordType_vi: "danh từ",
      definition_vi: ["Một quốc đảo ở Đông Á, nổi tiếng với văn hóa độc đáo và tiến bộ công nghệ."],
      example_vi: "Nhật Bản nổi tiếng với hoa anh đào vào mùa xuân.",
      slug: "japan",
    },
    {
      flashcardId: "country2",
      word: "Brazil",
      wordType: "noun",
      definition: ["The largest country in South America, known for its Amazon rainforest and vibrant culture."],
      example: "Brazil hosted the 2016 Summer Olympics.",
      phonetic: "/brəˈzɪl/",
      audioUrl: "",
      imageUrl: "./src/assets/brazil.jpeg",
      word_vi: "Bra-xin",
      wordType_vi: "danh từ",
      definition_vi: ["Quốc gia lớn nhất Nam Mỹ, nổi tiếng với rừng nhiệt đới Amazon và văn hóa sôi động."],
      example_vi: "Bra-xin đã đăng cai Thế vận hội Mùa hè 2016.",
      slug: "brazil",
    }
  ],
  "5": [
    {
      flashcardId: "sport1",
      word: "Tennis",
      wordType: "noun",
      definition: ["A racket sport that can be played individually against a single opponent or between two teams of two players each."],
      example: "She plays tennis every weekend.",
      phonetic: "/ˈtenɪs/",
      audioUrl: "",
      imageUrl: "./src/assets/tennis.jpeg",
      word_vi: "Quần vợt",
      wordType_vi: "danh từ",
      definition_vi: ["Môn thể thao dùng vợt có thể chơi đơn hoặc đôi."],
      example_vi: "Cô ấy chơi quần vợt mỗi cuối tuần.",
      slug: "tennis",
    },
    {
      flashcardId: "sport2",
      word: "Swimming",
      wordType: "noun",
      definition: ["The sport or activity of propelling oneself through water using the limbs."],
      example: "Swimming is a great full-body workout.",
      phonetic: "/ˈswɪmɪŋ/",
      audioUrl: "",
      imageUrl: "./src/assets/swimming.jpeg",
      word_vi: "Bơi lội",
      wordType_vi: "danh từ",
      definition_vi: ["Môn thể thao hoặc hoạt động di chuyển trong nước bằng cách sử dụng tay chân."],
      example_vi: "Bơi lội là một bài tập toàn thân tuyệt vời.",
      slug: "swimming",
    }
  ]
};